### ISSUE TITLE
Add ENTSO-E profiles?

### ISSUE THREAD

**Issue by caro-rli** [oemof/demandlib#10]
Does anyone remember if and how we decided on this issue? Does it make sense to add the ENTSO-E profiles to the demandlib? At the moment it would be comfortable for me to have these profiles and I would like to add them, but I'm not sure if we have decided against this.

**Comment by caro-rli** [comment]
Talked to @uvchik and we agreed on not introducing the entso-e load profiles to the demandlib. I will open a repository at rl-institut organization and add some of the profiles there as csv files.

**Comment by simnh** [comment]
I understand and agree that oemof is not the right place. But maybe we should provide a place where information about available data is collected that is closely connected to oemof activities?
