### ISSUE TITLE
Citation for the demandlib

### ISSUE THREAD

**Issue by gplssm** [oemof/demandlib#12]
Dear @oemof/demandlib,

I would like to cite the demandlib in a paper that will be submitted soon. Therefore, I plan to retrieve a DOI via Zenodo.
As we agreed for [oemof](https://github.com/oemof/oemof/issues/275) to have "oemof developer group" as author, I would apply same style here. Does anyone have objections with this? Otherwise I'll go for it at beginning of next week.

**Comment by ckaldemeyer** [comment]
> Dear @oemof/demandlib,
> 
> I would like to cite the demandlib in a paper that will be submitted soon. Therefore, I plan to retrieve a DOI via Zenodo.
> As we agreed for oemof to have "oemof developer group" as author, I would apply same style here. Does anyone have objections with this? Otherwise I'll go for it at beginning of next week.

:+1:

**Comment by gplssm** [comment]
http://doi.org/10.5281/zenodo.438786
