### ISSUE TITLE
Calculating COP for heatpump

### ISSUE THREAD

**Issue by Pyosch** [oemof/demandlib#15]
Hello everybody,

I've been working on creating loadshapes as well when I found this very nice project. I would like to contribute parts of my work to the demandlib. As a first suggestion I have a few lines to calculate the coefficient of performance for air and ground heatpumps. The formulas can be found in this publication:
https://www.researchgate.net/publication/255759857_A_review_of_domestic_heat_pumps

Do you think this is an appropriate addition?
In which file should the code be added? In my Fork I wrote it into the bdew.py file as a function of the HeatBuilding class.

Greetings,
Pyosch

**Comment by henhuy** [comment]
Hey @Pyosch,

some people (@birgits ?) at our institute already implemented a cop-heating alogrithm at https://github.com/rl-institut/appBBB/blob/master/appBBB/helper_heat_pump.py

I don't know if it fits your needs - maybe you could easily use it or adapt it?!
Just wanted to mention it, before you dive into coding...

**Comment by simnh** [comment]
But maybe it would also be nice to have it in the demand lib right and not inside an app somewhere. @Pyosch I really like the idea!

**Comment by Pyosch** [comment]
@henhuy : after a first quick scan your solution seems to be way more complex than the one I have. Would be interesting to compare the results...

@simnh : ok, I'll try to clean up my code a little and then push the branch

**Comment by uvchik** [comment]
From my point of view the demandlib focuses on the demand side of an energy system, so I would not expect such equations here.

Therefore i would suggest to put it in the [oemof-heat-components repository](https://github.com/oemof/oemof-heat-components) (I added an empty file there) or to integrate it into [TESPy](https://github.com/oemof/tespy), which might be done already but you could compare your approach.

**Comment by uvchik** [comment]
I do not know if you got me right. 

I do not want to delete the code, I would like to refactor is from a method to a function and put it to another place where it is more likely, that people will find it.

@henhuy If your code works you could also copy it to the oemof-heat-components repository. This repository is meant as a collection for such approaches. 

In the first step, we want to collect approaches and in a second step we will discuss how to make such approaches available for other users. Creating a library, integrate it in existing libraries, just keep it as a collection,.....

**Comment by uvchik** [comment]
As @Pyosch is contributing [here](https://github.com/oemof/oemof-thermal/pull/7) we can close this issue.
