### ISSUE TITLE
Missing dynamisation function for electric load profiles

### ISSUE THREAD

**Issue by busiing** [oemof/demandlib#17]
I couldn't find the implementation of the BDEW dynamization function ("Dynamisierungsfunktion") to smoothen the seasonal edges of the H0 slp:

f(x) = -3,92 * 10^-10 * x^4 + 3,2 * 10^-7 * x³ - 7,02 * 10^-5 * x²+0,0021 * x +1,24

![Figure_3](https://user-images.githubusercontent.com/25903724/57928846-0bdc2780-78b2-11e9-82dc-e2ea67fb135f.png)

Did I miss this or is it missing?

**Comment by uvchik** [comment]
It is missing.
