### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by uvchik** [oemof/demandlib#2]
@oemof/demandlib: We should write a documentation comparable to the one of the feedinlib (we can use the structure of the feedinlib documentation to start with).
- Setup a sphinx documentation
- Create a Readme file
- Check Docstrings

**Comment by uvchik** [comment]
http://demandlib.readthedocs.io

**Comment by caro-rli** [comment]
I added some content to readme and documentation, but still not sufficiently...

**Comment by uvchik** [comment]
@gplssm Could you update the example section of README to explain how to execute the examples.
