### ISSUE TITLE
It seems the highes possible share of new buildings (Neubau) is 57%

### ISSUE THREAD

**Issue by jakob-wo** [oemof/demandlib#20]
Hi everyone,

I am new to the demandlib and the BDEW profiles.
Right know I am trying to figure out what kind of buildungs a certain set of arguments represent. As far as I understand it is not possible to create a profile for a stock of buildings that consists mainly (>60%) of new buildings (ger. "Neubauten"). 
Is that correct? 
And does anyone of you know a way to do so, like using another set of sigmoid parameters?

Thanks!

**Comment by uvchik** [comment]
There are several documentations about BDEW profiles in general (german). A brief overview can be found in the [documentation](https://demandlib.readthedocs.io/en/latest/description.html#bdew).

You can create different specific demand time series and multiply them with the annual demand of each type. If your annual demand is 1000 GWh you can multiply 600 GWh with the demand time series closed to what you call "Neubauten" and 400 GWh with another time series. You do not need to combine the different types beforehand.
