### ISSUE TITLE
Release v0.1.9

### ISSUE THREAD

**Issue by p-snft** [oemof/demandlib#23]
There are several issues fixed in dev (see next comment on https://github.com/oemof/demandlib/pull/21#pullrequestreview-439009683). There should be a new release.

**Comment by lennsea** [comment]
I see that the newest version already fixed this issue. Version 0.1.8 on PiPy still contains the slow for loop which was the reason for this issue. Can you please release a newer version of the demandlib to PiPy?

**Comment by p-snft** [comment]
Thanks for the reminder. I will have a look into it.

**Comment by p-snft** [comment]
The release is out: https://pypi.org/project/demandlib/0.1.9/
