### ISSUE TITLE
Setup requirement of pandas

### ISSUE THREAD

**Issue by SabineHaas** [oemof/demandlib#27]
The requirement of demandlib for pandas is [`pandas >= 0.18.0, < 0.25`](https://github.com/oemof/demandlib/blob/d10b09b9c31e3f87a49a66fc0d37b4c6954684ae/setup.py#L24).

I install the demandlib in a package that uses xarray, which is incompatible with demandlib as it requires pandas >= 0.25.  

Do you see a problem in loosening the limit and allowing pandas < 1.1.0 or `pandas >= 0.25.`? I didn't have a problem with that creating power and heat demand profiles but as there are no tests of the demandlib, I cannot be sure, of course.

**Comment by p-snft** [comment]
I added a PR with an updated setup.py. Would you check it, @SabineHaas?
