### ISSUE TITLE
Release of v0.1.7

### ISSUE THREAD

**Issue by uvchik** [oemof/demandlib#31]
* [x] Optional: Open a release branch to avoid conflicts with other uses while the release progress.
* [x] Run examples and tests check the Travis-CI results
* [x] If you have failing test fix them or postpone the release.
* [x] Check the whatsnew-file.
* [x] Check if the *latest* documentation looks right at [readthedocs](http://oemof.readthedocs.org).
* [x] Change the version number everywhere!!! [TODO] (e.g. from 0.2.1dev to 0.2.1)
* [x] If everything seems to work, merge the release branch into the master branch. (--no-ff)
* [x] Open a working python3 virtual environment.
* [x] Make sure that the release tools are up-to-date: ```pip install --upgrade setuptools wheel twine```
* [x] Make sure you are on the commit you want to release and create the package: ```python3 setup.py sdist bdist_wheel```
* [x] Check the package with twine: ```twine check dist/*```
* [x] If errors occur fix them or postpone the release.
* [x] Set a [release on github](../releases). Select the **master** branch (default: dev)! A label is set automatically.
* [x] Use `git fetch` to see the label in your local master branch.
* [x] If everything works as expected you can now upload the package version to PyPI: ```twine upload dist/*```
* [x] Merge the release branch into the dev branch. (--no-ff)
* [x] Remove the obsolete release branch.
* [x] Prepare the dev branch for further development: Adapt the version number. Also add a link in the [whatsnew.rst file](../tree/dev/doc/whats_new.rst). Open the file locally or use the *RAW* button to see the links.

**Comment by p-snft** [comment]
You might want to set this default to false, to maintain the previous bahaviour:

https://github.com/oemof/demandlib/blob/cd6a83d6d3d4b10e0e129138cb3d00f5cba5d9af/demandlib/bdew.py#L127

**Comment by uvchik** [comment]
...or adding a warning?

I principally agree that using the dynamic function should be the default.

**Comment by p-snft** [comment]
It should, once it does not have performance issues any more.

**Comment by uvchik** [comment]
So I will add a `FutureWarning` that in future the default value will be `True` but for the next release we will set it to `False`, okay?

**Comment by p-snft** [comment]
I did this now. (I heard complaints about the officially released version requiring legacy versions of other packages.)

**Comment by p-snft** [comment]
Done
