### ISSUE TITLE
Compilation of heat_demand_example fails

### ISSUE THREAD

**Issue by indiebenni** [oemof/demandlib#32]
Hello,
I'm new to the demandlib package and wanted to figure out what the source of this error might be: 

Compilation of the heat_demand_example always leads to the error 
![image](https://user-images.githubusercontent.com/74677159/99569696-4061ff80-29d1-11eb-94d2-b3c33d8f8901.png)

which I am not able to sort out alone. I updated the oemof, demandlib and pandas package. The power example instead works completely fine. I'm using Python 3.8.3 Would be really nice if someone could help me out with this.

Regards,
Benjamin

**Comment by uvchik** [comment]
Could you provide the whole error message? 

Make sure that you do not use the actual example from github (v0.1.7b1) with the actual demandlib version from pypi (v0.1.6.).

**Comment by indiebenni** [comment]
I now successfully ran the code with not the most current version of Anaconda, Spyder and Python, so I assume it was probably due to my software installations. Thank you anyway for the assistance
