### ISSUE TITLE
Explanation of the building_class parameter of HeatBuilding class is missing in the documentation

### ISSUE THREAD

**Issue by MaGering** [oemof/demandlib#41]
The explanation of the values (1-11) for the parameter `building_class` is missing. In [this document](https://www.eko-netz.de/files/eko-netz/download/3.5_standardlastprofile_bgw_information_lastprofile.pdf) `building_class` is described. So the docs should be updated with this information.

**Comment by jnnr** [comment]
Thanks for bringing this up. How about:

The parameter `building_class` (German: Baualtersklasse) can assume values in range 1-11. The building_class describes the ratio of buildings older than xxx in the building stock. See [this document, page ](https://www.eko-netz.de/files/eko-netz/download/3.5_standardlastprofile_bgw_information_lastprofile.pdf) for more information.

Please update as you like. As soon as we are happy with it, you can open a PR.

**Comment by uvchik** [comment]
@MaGering Could you provide a PR or a concrete suggestion. Any contribution is welcome.
