### ISSUE TITLE
How to use this  library to generate electricity demand profile for a business?

### ISSUE THREAD

**Issue by ShantanuKumar** [oemof/demandlib#43]
I am trying to generate an electricity demand profile for a business whose  yearly consumption is known.
How would I do it? Sorry my German is not that great to understand the underlying documents which are mentioned in the documentation.

**Comment by uvchik** [comment]
Did you have a look at the [example](https://github.com/oemof/demandlib/blob/dev/examples/electricity_demand_example.py)?

Be aware that the result is in power units for a 15 minute interval. So you have to divide the result by 4 to get a typical energy unit. We may change that behaviour in the future to make it more intuitive.

```python
import demandlib.bdew as bdew

# read standard load profiles
e_slp = bdew.ElecSlp(2020)
print(e_slp.slp_frame.columns)

# multiply given annual demand with timeseries
elec_demand = e_slp.get_profile({"g0": 5000})
print(elec_demand.sum().div(4))
```

**Comment by uvchik** [comment]
We also should add this to the documentation:

# German (original):
G0 | Gewerbe allgemein | Gewogener Mittelwert der Profile G1-G6
-- | -- | --
G1 | Gewerbe werktags 8–18 Uhr | z. B. Büros, Arztpraxen, Werkstätten, Verwaltungseinrichtungen
G2 | Gewerbe mit starkem bis überwiegendem Verbrauch in den Abendstunden | z. B. Sportvereine, Fitnessstudios, Abendgaststätten
G3 | Gewerbe durchlaufend | z. B. Kühlhäuser, Pumpen, Kläranlagen
G4 | Laden/Friseur |  
G5 | Bäckerei mit Backstube |  
G6 | Wochenendbetrieb | z. B. Kinos
G7 | Mobilfunksendestation | durchgängiges Bandlastprofil
L0 | Landwirtschaftsbetriebe allgemein | Gewogener Mittelwert der Profile L1 und L2
L1 | Landwirtschaftsbetriebe mit Milchwirtschaft/Nebenerwerbs-Tierzucht |  
L2 | Übrige Landwirtschaftsbetriebe |  
H0 | Haushalt

# British English (translation):

I am not sure how to translate `"Gewerbe"` -> business, commerce, trade ? 
G0 | General trade | Weighted average of profiles G1-G6
-- | -- | --
G1 | Business on weekdays 8 a.m. - 6 p.m. | e.g. offices, doctors' surgeries, workshops, administrative facilities
G2 | Businesses with heavy to predominant consumption in the evening hours | e.g. sports clubs, fitness studios, evening restaurants
G3 | Continuous trade | e.g. cold stores, pumps, sewage treatment plants
G4 | Shop/barber shop |  
G5 | Bakery with bakery |  
G6 | Weekend operation | e.g. cinemas
G7 | Mobile phone transmitter station | continuous band load profile
L0 | General farms | Weighted average of profiles L1 and L2
L1 | Farms with dairy farming/part-time livestock farming |  
L2 | Other farms |  
H0 | Household

**Comment by ShantanuKumar** [comment]
Hi @uvchik , thank you for the help. Yeah I did check the examples. I was bit confused about which load profile to use from the multiple electrical load profiles as mentioned [here](https://demandlib.readthedocs.io/en/latest/description.html#electrical-profiles)

**Comment by ShantanuKumar** [comment]
> We also should add this to the documentation:
> # German (original):
> G0 	Gewerbe allgemein 	Gewogener Mittelwert der Profile G1-G6
> G1 	Gewerbe werktags 8–18 Uhr 	z. B. Büros, Arztpraxen, Werkstätten, Verwaltungseinrichtungen
> G2 	Gewerbe mit starkem bis überwiegendem Verbrauch in den Abendstunden 	z. B. Sportvereine, Fitnessstudios, Abendgaststätten
> G3 	Gewerbe durchlaufend 	z. B. Kühlhäuser, Pumpen, Kläranlagen
> G4 	Laden/Friseur 	
> G5 	Bäckerei mit Backstube 	
> G6 	Wochenendbetrieb 	z. B. Kinos
> G7 	Mobilfunksendestation 	durchgängiges Bandlastprofil
> L0 	Landwirtschaftsbetriebe allgemein 	Gewogener Mittelwert der Profile L1 und L2
> L1 	Landwirtschaftsbetriebe mit Milchwirtschaft/Nebenerwerbs-Tierzucht 	
> L2 	Übrige Landwirtschaftsbetriebe 	
> H0 	Haushalt 	
> # British English (translation):
> 
> I am not sure how to translate `"Gewerbe"` -> business, commerce, trade ?
> G0 	General trade 	Weighted average of profiles G1-G6
> G1 	Business on weekdays 8 a.m. - 6 p.m. 	e.g. offices, doctors' surgeries, workshops, administrative facilities
> G2 	Businesses with heavy to predominant consumption in the evening hours 	e.g. sports clubs, fitness studios, evening restaurants
> G3 	Continuous trade 	e.g. cold stores, pumps, sewage treatment plants
> G4 	Shop/barber shop 	
> G5 	Bakery with bakery 	
> G6 	Weekend operation 	e.g. cinemas
> G7 	Mobile phone transmitter station 	continuous band load profile
> L0 	General farms 	Weighted average of profiles L1 and L2
> L1 	Farms with dairy farming/part-time livestock farming 	
> L2 	Other farms 	
> H0 	Household

Yes this helps.

**Comment by uvchik** [comment]
Sorry, I totally forgot that in the docs only heat profiles are translated at the moment. We will add the table above to the documentation.

**Comment by uvchik** [comment]
See #44
