### ISSUE TITLE
Unclear understanding of the file shlp_hours_factors.csv

### ISSUE THREAD

**Issue by AlexJew** [oemof/demandlib#56]
Hello everyone, 

My name is Alexandre Jewell, and I work at a company focused on energy planning. We are currently working on the use of the BDEW hourly profiles for estimating the potential electricity flows within an energy community. To do so, I was thinking of using the standard load profiles from the BDEW, and I've got to thank you for how you structured them and made them so much clearer in your file [shlp_hours_factors.csv](https://github.com/oemof/demandlib/blob/dev/src/demandlib/bdew/bdew_data/shlp_hour_factors.csv) contained within the folder [bdew_data](https://github.com/oemof/demandlib/tree/dev/src/demandlib/bdew/bdew_data)

However, after reading the documentation, I wasn't able to get a complete understanding of the structure of it. Here are my questions: 

1. What is the difference between the column `building_class` and the column `shlp_type` ? 
2. To which temperatures do the intervals `temp_intervall_01`, `temp_intervall_02`, etc. correspond to ? 

<img width="1431" alt="image" src="https://github.com/oemof/demandlib/assets/32110882/ed8ca80a-7858-4f18-84f9-fa5d2b23550b">

Thank you very much for the help and the overall effort you've been putting into open source code so far ! 

Kind regards, 

Alex

**Comment by p-snft** [comment]
Hi @AlexJew, thanks for asking. The first thing is rather easy to explain: the `building_class` (Baualtersklasse) expresses the age of the building (cf. https://demandlib.readthedocs.io/en/latest/bdew.html#heat-profiles). To my knowledge, the latter is also due to considering intervals, but this time for the temperature. But honestly, I am not an expert for this specific aspect.

**Comment by AlexJew** [comment]
Hello, thank you very much for the reply. I believed that I was actually confused by the difference between the selp and the shlp series. It should be good now. I'll close the thread, and reopen it only in case I have some new questions :)
