### ISSUE TITLE
Release 0.2.1

### ISSUE THREAD

**Issue by birgits** [oemof/demandlib#67]
Thank you for the PR @maurerle and merging it @p-snft. I would appreciate it, if we could make a new release soon. If nothing speaks against it from your side, I could prepare a release PR?

**Comment by p-snft** [comment]
I agree. Could you help also merging #60 before? (An erroneous example is something I don't want in the known issues if it can be avoided.) However, I'm currently lacking the time to resolve the conflicts.

**Comment by birgits** [comment]
Sure, I'll have a look at it tomorrow!

**Comment by p-snft** [comment]
Released with #69.
