### ISSUE TITLE
need help understanding the get_profile function from the electrical profile

### ISSUE THREAD

**Issue by juebarbosa** [oemof/demandlib#70]
i really do not understand why the whole load profile is multiplied by 4 in this function:

i thought this function was to adjust the whole profile to my annual demand, but then it multiplies my annual demand by four....

```python
def get_profile(self, ann_el_demand_per_sector):
        """Get the profiles for the given annual demand

        Parameters
        ----------
        ann_el_demand_per_sector : dictionary
            Key: sector, value: annual value

        Returns
        -------
        pandas.DataFrame : Table with all profiles

        """
        return (
            self.slp_frame.multiply(
                pd.Series(ann_el_demand_per_sector), axis=1
            ).dropna(how="all", axis=1)
            * 4
        )
```

**Comment by p-snft** [comment]
Hi @juebarbosa! The multiplication by 4 is because the original time series is in Energy (MWh), but we return a time series expressing power (MW). For example, an Energy of 2 kWh supplied in a time of 15 Minutes makes 8 kW. Probably, we should extend the documentation so that it is clear that we return a power time series. What do you think, would have helped you best?

**Comment by juebarbosa** [comment]
Thank you very much! Your help is very appreciated.
So in my case that the annual consumption is given in kWh because it is for only one house, i can erase the multiplication by 4, since i want to get a Graph in the end that is it aldo in kWh, right?

And yeah, maybe it would be nice to make it more clear that a power time series is returned.

**Comment by p-snft** [comment]
Honestly, I think one value in kWh every 15 minutes is more confusing than helping. In fact, you move the factor of 4 from the explicit multiplication to the unit (1 h/15 min = 4).

Let me give an analog example: You can either name the speed (in km/h) or the distance (in km). If you name one value every hour, both have the same numeric value. However, if you go to a different resolution, you might end up having 3.33 km every 10 Minutes, 5 km every 15 minutes, 20 km in one hour or 20 km/h independent from the resolution. In my opinion, the absolute value should not depend on the sampling frequency, so in this case naming speed is the better alternative.

**Comment by juebarbosa** [comment]
Sorry for my confunsing self!  hahah I completly agree that having kWh every 15 Min does not make sense. Now i am using the original code and resampling it to become hourly values. So i am using the code as it is in the source: 
def get_profile(self, ann_el_demand_per_sector):
        """Get the profiles for the given annual demand

        Parameters
        ----------
        ann_el_demand_per_sector : dictionary
            Key: sector, value: annual value

        Returns
        -------
        pandas.DataFrame : Table with all profiles

        """
        return (
            self.slp_frame.multiply(
                pd.Series(ann_el_demand_per_sector), axis=1
            ).dropna(how="all", axis=1)
            * 4
        )
 

and then resampling like added in the example here in the repository:
# Resample 15-minute values to hourly values.
elec_demand_resampled = elec_demand.resample("h").mean()

So now i have my result in kW every hour right?

Thanks for the help
Best Regards

**Comment by p-snft** [comment]
Sounds good. I'll close this now.
